package Parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATE = 15;
  public static final int LV = 4;
  public static final int AND = 6;
  public static final int RV = 5;
  public static final int ELSE = 25;
  public static final int DOTCOMMA = 19;
  public static final int PLUS = 8;
  public static final int INT = 22;
  public static final int OR = 7;
  public static final int LP = 2;
  public static final int WHILE = 26;
  public static final int SCANF = 28;
  public static final int RP = 3;
  public static final int IF = 24;
  public static final int PRINTF = 27;
  public static final int ID = 29;
  public static final int COMMA = 20;
  public static final int GREAT = 14;
  public static final int EOF = 0;
  public static final int MAIN = 21;
  public static final int DIV = 11;
  public static final int CONST = 30;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int EQ = 16;
  public static final int MIN = 10;
  public static final int LESSE = 13;
  public static final int NEQ = 17;
  public static final int MUL = 9;
  public static final int LESS = 12;
  public static final int DOUBLE = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LP",
  "RP",
  "LV",
  "RV",
  "AND",
  "OR",
  "PLUS",
  "MUL",
  "MIN",
  "DIV",
  "LESS",
  "LESSE",
  "GREAT",
  "GREATE",
  "EQ",
  "NEQ",
  "ASSIGN",
  "DOTCOMMA",
  "COMMA",
  "MAIN",
  "INT",
  "DOUBLE",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTF",
  "SCANF",
  "ID",
  "CONST"
  };
}

